# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='landing',
            new_name='Subscriber',
        ),
    ]
